{% set version = '1.1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mlmetrics
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MLmetrics_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MLmetrics/MLmetrics_{{ version }}.tar.gz
  sha256: 777f1b76b16837387b830e2b65304ede234b9299d17efd09c7fd403356122118

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1004
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rocr
  run:
    - r-base
    - r-rocr

test:
  commands:
    - $R -e "library('MLmetrics')"           # [not win]
    - "\"%R%\" -e \"library('MLmetrics')\""  # [win]

about:
  home: http://github.com/yanyachen/MLmetrics
  license: GPL-2.0-only
  summary: A collection of evaluation metrics, including loss, score and utility functions, that
    measure regression, classification and ranking performance.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
