appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UqaWAh+N7sd8p5EbnxI2WvXfn6TIE7KwLH4uIOYFcMHDIT5MFlq4ze2lYbqfSku9LM4Q+soNKouEnnG3guuFqLgXX7PNUR8oVEw+ePINTwyzAPWhl3dn6X9miqLwr8y2L9dLoMUoXUjxi1vavc7w6dpOWRgtEGBHcu8pwLcxfIsUWuBNTMF+4zdUS50W0AfxoBKrzBNDncOuZcUwfzXZo2aB308bzZZHeFmL9ZdXdatCxUpBXiruXB5TkfDDZcbjsA4KoeD7qC3V5WACr44n0kszbAyAMAlkHZ1liZuhBsjcpzhRQgCiVT3ixQSunJpo6T+7gBV2Lj2h0lbj8JwGd1lu+wvV+ylbcxdYE0L5/onwnLsDZ2d1AsarbNY9PsVSWLU3PDiYKcC3APBoL7N0IUpj7BLgKck4cCiecnTJQ3LHAh6tBB1k+H9Uhl+A+l/1SgFXeCKKy3nyiMF2w57qTNr9oAjd3b01M+yh+rDNBCO8JqCwjDb7MuQTIxX27TNj3cmFJbWT5r88yDJ5yij0JFje54AgwwxTYxfYpDTBJf9P9Qoubi0te9MZ2Qe19VtVvXT1Xt8NlR7wAbHymb0uQowUYxFuGJ6d/N/+8Xn9RaE3qr6CI4rDYIlxucLF6JeKfipIaO2dRXBELXMsQT39oqa4ElOLtntp4Eg0cHi1w6E=}
